// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2oTm7jMZ4fRoEWFqn7Guc3eexGdUJ8g',
    appId: '1:970011403043:web:f966ed1ff7e04e11e2a296',
    messagingSenderId: '970011403043',
    projectId: 'incrementproject-ff99e',
    authDomain: 'incrementproject-ff99e.firebaseapp.com',
    storageBucket: 'incrementproject-ff99e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXloZd8xJYxd9MLvk1eTYCKJayTZUMS0w',
    appId: '1:970011403043:android:17eab0ebaf2b686ee2a296',
    messagingSenderId: '970011403043',
    projectId: 'incrementproject-ff99e',
    storageBucket: 'incrementproject-ff99e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVyg0JgAVhVPA-CI4Ysw8c1jM4ES8msxc',
    appId: '1:970011403043:ios:36b8b17cb46c05a8e2a296',
    messagingSenderId: '970011403043',
    projectId: 'incrementproject-ff99e',
    storageBucket: 'incrementproject-ff99e.appspot.com',
    iosBundleId: 'com.example.incrementButtonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVyg0JgAVhVPA-CI4Ysw8c1jM4ES8msxc',
    appId: '1:970011403043:ios:36b8b17cb46c05a8e2a296',
    messagingSenderId: '970011403043',
    projectId: 'incrementproject-ff99e',
    storageBucket: 'incrementproject-ff99e.appspot.com',
    iosBundleId: 'com.example.incrementButtonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2oTm7jMZ4fRoEWFqn7Guc3eexGdUJ8g',
    appId: '1:970011403043:web:d72c11876e2e5dc9e2a296',
    messagingSenderId: '970011403043',
    projectId: 'incrementproject-ff99e',
    authDomain: 'incrementproject-ff99e.firebaseapp.com',
    storageBucket: 'incrementproject-ff99e.appspot.com',
  );
}
